services:
  postgres:
    image: postgres:15.18-bookworm
    container_name: smartserve-postgres
    environment:
      POSTGRES_DB: smartserve_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - smartserve_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d smartserve_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smartserve-net
    restart: unless-stopped

  smartserve-api:
    image: pisethmao/smartserve-api:latest
    container_name: smartserve-api
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - image-backup-vol:/app/filestorage/images
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartserve_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: smartserve_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - smartserve-net
    restart: unless-stopped

volumes:
  smartserve_postgres_data:
  image-backup-vol:

networks:
  smartserve-net:
    driver: bridge