spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartserve_db
    username: postgres
    password: Piseth1711*#
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
scalar:
  enabled: true
  path: /scalar
  url: /v3/api-docs
  page-title: SmartServe API Reference